// vue-music-explorer/src/components/SongItem.vue
<template>
  <li>
    <div class="thumbnail">
      <LazyImg :lazySrc="song.attributes.artwork.url | formatArtwork(60)" alt/>
    </div>
    <p class="index" v-if="index !== null">{{index +1 }}</p>
    <div class="label">
      <h3>{{song.attributes.name}}</h3>
      <p v-if="song.attributes.artistName">{{song.attributes.artistName}}</p>
    </div>
    <p
      class="note"
      v-if="song.attributes.durationInMillis"
    >{{song.attributes.durationInMillis | msToMins}}</p>
  </li>
</template>
<style scoped>
li {
  display: flex;
  justify-content: flex-start;
  align-items: center;
}
.thumbnail {
  height: 80px;
  width: 80px;
  padding-right: 10px;
}
.label {
  display: block;
  flex: 1;
  white-space: nowrap;
  overflow: hidden;
}
.label h3, .label .note * {
  overflow: hidden;
  text-overflow: ellipsis;
}
.index {
  font-variant-numeric: tabular-nums;
  text-align: right;
  padding-right: 10px;
}
.note {
  font-variant-numeric: tabular-nums;
}

</style>

<script lang="ts">
import { Component, Vue, Prop } from "vue-property-decorator";

@Component({
  components: {
    LazyImg: () => import("@/components/LazyImg.vue")
  }
})
export default class SongItem extends Vue {
  @Prop() song!: any;
  @Prop() index!: number;
}
</script>

// react-music-explorer/src/components/song-item/SongItem.tsx
import { LazyImg } from '../lazyimg/LazyImg';
import { formatArtwork } from '../../pipes/formatArtwork';
import { msToMins } from '../../pipes/msToMins';
import React from 'react';
import './songitem.css';
export default function SongItem(props: { song: any; index: number }) {
  return (
    <li>
      <div className="thumbnail">
        <LazyImg
          src={formatArtwork(props.song.attributes.artwork.url, 60)}
          alt="Artwork"
        />
      </div>
      {props.index !== null ? <p className="index">{props.index + 1}</p> : null}

      <div className="label">
        <h3>{props.song.attributes.name} </h3>
        {props.song.attributes.artistName ? (
          <p>{props.song.attributes.artistName}</p>
        ) : null}
        {props.song.attributes.artistName ? (
          <p>{props.song.attributes.artistName}</p>
        ) : null}
      </div>
      {props.song.attributes.durationInMillis ? (
        <p className="note">
          {msToMins(props.song.attributes.durationInMillis)}
        </p>
      ) : null}
    </li>
  );
}
