// vue-music-explorer/src/views/Landing.vue
<template>
  <div>
    <h3>Welcome to Star Track</h3>
    <p>Star Track is a simple way to interact with Apple Music.</p>
    <router-link to="/browse">Get Started</router-link>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
@Component({})
export default class LandingPage extends Vue {}
</script>

// react-music-explorer/src/pages/landing/Landing.tsx
import React from 'react';
import { Link } from 'react-router-dom'
export default function LandingPage(props: any) {
  return (
    <>
      <h3> Welcome to Star Track</h3>
      <p>Star Track is a simple way to interact with Apple Music.</p>
      <Link to='browse'>Get Started</Link>
    </>
  );
}
