// react/src/components/preview-header/PreviewHeader.tsx
import { LazyImg } from '../lazyimg/LazyImg';
import { formatArtwork } from '../../pipes/formatArtwork';
import React from 'react';
import './preview-header.css';
export function PreviewHeader(props: { collection: any }) {
  const { duration, bg } = getExtras(props.collection);

  return (
    <div className="artwork-artwork" style={{ backgroundImage: bg }}>
      <div className="artwork-header">
        <div className="header-artwork">
          <LazyImg
            src={formatArtwork(props.collection.attributes.artwork.url, 1500)}
            alt="Artwork"
          />
        </div>
        <div className="album-detail">
          <h3>{props.collection.attributes.name}</h3>

          <p>
            {props.collection.attributes.artistName
              ? props.collection.attributes.artistName
              : props.collection.attributes.curatorName}
          </p>
          <p>
            {props.collection.attributes.description
              ? props.collection.attributes.description.short
              : props.collection.attributes.genreNames[0]}
          </p>

          <p>
            {props.collection.relationships.tracks.data.length} Songs,{' '}
            {formatDuration(duration)}
          </p>
        </div>
      </div>
    </div>
  );
}
function getExtras(collection: any): { duration: number; bg: string } {
  let duration = 0;
  let bg = '';
  for (const song of collection.relationships.tracks.data) {
    if (song.attributes.durationInMillis) {
      duration += song.attributes.durationInMillis;
    }
  }
  bg = `url("${(window as any).MusicKit.formatArtworkURL(
    { url: collection.attributes.artwork.url },
    1000,
    1000
  )}`;
  return { duration, bg };
}
function formatDuration(val: number) {
  const { hours, minutes } = (window as any).MusicKit.formattedMilliseconds(
    val
  );
  const hourTime = hours === 0 ? `` : `${hours} hours, `;
  const minutesTime = `${minutes} minutes`;
  return `${hourTime} ${minutesTime} `;
}

// angular-music-explorer/src/app/components/preview-header/preview-header.component.ts
import {
  Component,
  EventEmitter,
  Input,
  Output,
  HostBinding,
  ChangeDetectionStrategy,
  ChangeDetectorRef
} from '@angular/core';
import { DomSanitizer, SafeStyle } from '@angular/platform-browser';
@Component({
  selector: 'preview-header',
  templateUrl: './preview-header.component.html',
  styleUrls: ['./preview-header.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class PreviewHeaderComponent {
  @HostBinding('style.background-image') bg: SafeStyle = '';

  @Input()
  get collection() {
    return this._collection;
  }
  set collection(val: any) {
    this._collection = val;
    if (this._collection) {
      for (const song of this._collection.relationships.tracks.data) {
        if (song.attributes.durationInMillis) {
          this.duration += song.attributes.durationInMillis;
        }
      }

      this.bg = this.sanitizer.bypassSecurityTrustStyle(
        `url("${(window as any).MusicKit.formatArtworkURL(
          { url: this._collection.attributes.artwork.url },
          1000,
          1000
        )}")`
      );
    this.cd.markForCheck();
    }
  }

  public duration = 0;
  private _collection: any = null;
  constructor(private sanitizer: DomSanitizer, private cd: ChangeDetectorRef) {}

  formatDuraction(val: number) {
    const { hours, minutes } = (window as any).MusicKit.formattedMilliseconds(val);
    const hourTime = hours === 0 ? `` : `${hours} hours, `;
    const minutesTime = `${minutes} minutes`;
    return `${hourTime} ${minutesTime} `;
  }
}


<div class="artwork-header">
  <div class="album-info" *ngIf="collection">
    <lazy-img class="header-artwork" [src]="collection.attributes.artwork.url | formatArtworkUrl:1500"></lazy-img>
    <div class="album-detail">
      <h3>{{collection.attributes.name}}</h3>
      <p>{{ collection.attributes.artistName ? collection.attributes.artistName : collection.attributes.curatorName }}
      </p>
      <p>{{ collection.attributes.description ? collection.attributes.description.short : collection.attributes.genreNames[0]}}</p>
      <p>{{collection.relationships.tracks.data.length}} Songs, {{formatDuraction(duration)}}</p>
    </div>
  </div>
</div>
