// vue/src/views/Search.vue
<template>
  <div>
    <label>
      <input
        placeholder="Artists, Songs, Lyrics, and More"
        :value="term"
        @input="handleInputChange($event)"
        type="search"
      >
    </label>

    <ul v-if="albumResults">
      <h2>Albums</h2>
      <router-link
        v-for="(album, idx) in albumResults"
        :to="'/album/'+album.id"
        v-bind:key="album.id"
      >
        <SongItem :song="album" :index="idx"/>
      </router-link>
    </ul>
    <ul v-if="playlistResults">
      <h2>Playlists</h2>
      <router-link
        v-for="(album, idx) in playlistResults"
        :to="'/playlist/'+album.id"
        v-bind:key="album.id"
      >
        <SongItem :song="album" :index="idx"/>
      </router-link>
    </ul>
  </div>
</template>
<style scoped>
ul {
  padding: 0;
}
h2 {
  position: sticky;
  top: 0;
  background: white;
}
</style>
<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { musicKitService } from "@/services/musickit-service";
import { Subject } from "rxjs";
import { debounceTime, filter, switchMap } from "rxjs/operators";
@Component({
  components: {
    SongItem: () => import("@/components/SongItem.vue")
  }
})
export default class AlbumPage extends Vue {
  isLoading: boolean = true;
  albumResults: any[] | null = null;
  playlistResults: any[] | null = null;
  term = "";
  onInput$ = new Subject<string>();

  mounted() {
    this.onInput$
      .pipe(
        filter((term: any) => {
          if (term) return term;
          this.albumResults = null;
          this.playlistResults = null;
        }),
        debounceTime(500),
        switchMap((term: string) => musicKitService.search(term))
      )
      .subscribe((results: any) => {
        this.albumResults = results.albums.data;
        this.playlistResults = results.playlists.data;
      });
  }
  handleInputChange(event: any) {
    this.term = event.target.value
    this.onInput$.next(event.target.value);
  }
}
</script>

// react-music-explorer/src/pages/search/Search.tsx
import React, { Component, Suspense, lazy } from 'react';
import { Link } from 'react-router-dom';
import { Subject } from 'rxjs';
import { filter, debounceTime, switchMap } from 'rxjs/operators';
import { musicKitService } from '../../services/musickit-service';
const SongItem = lazy(() => import('../../components/song-item/SongItem'));
import './search.css';
export default class SearchPage extends Component<
  any,
  {
    term: string;
    isLoading: boolean;
    isError: boolean;
    albumResults: any;
    playlistResults: any;
  }
> {
  private onInput$: any;
  constructor(props: any) {
    super(props);
    this.state = {
      term: '',
      isLoading: false,
      isError: false,
      playlistResults: null,
      albumResults: null
    };
    this.onInput$ = new Subject<string>();
    this.onInput$
      .pipe(
        filter((term: any) => {
          console.log('term', term);
          if (term) return term;

          console.log('no terms');
          this.setState({
            ...this.state,
            albumResults: [],
            playlistResults: []
          });
          console.log(this.state);
        }),
        debounceTime(500),
        switchMap((term: string) => musicKitService.search(term))
      )
      .subscribe((results: any) => {
        this.setState({
          ...this.state,
          albumResults: results.albums.data,
          playlistResults: results.playlists.data
        });

        console.log(this.state);
      });
  }

  handleInputChange(ev: any) {
    this.onInput$.next(ev.target.value);
    this.setState({ ...this.state, term: ev.target.value });
  }
  render() {
    return (
      <>
        <label>
          <input
            placeholder="Artists, Songs, Lyrics, and More"
            value={this.state.term}
            onChange={ev => this.handleInputChange(ev)}
            type="search"
          />
        </label>
        <Suspense fallback={<div>Loading...</div>}>
          {this.state.albumResults && this.state.playlistResults ? (
            <>
              <ul>
                <h2>Albums</h2>
                {this.state.albumResults.map((album: any, idx: number) => (
                  <Link to={'/album/' + album.id} key={album.id}>
                    <SongItem song={album} index={idx} />
                  </Link>
                ))}
              </ul>

              <ul>
                <h2>Playlists</h2>
                {this.state.playlistResults.map(
                  (playlist: any, idx: number) => (
                    <Link to={'/playlist/' + playlist.id} key={playlist.id}>
                      <SongItem song={playlist} index={idx} />
                    </Link>
                  )
                )}
              </ul>
            </>
          ) : null}
        </Suspense>
        {}
      </>
    );
  }
}
