// react-music-explorer/src/pages/album/Album.tsx
import React, { Component } from 'react';
import { musicKitService } from '../../services/musickit-service';
import { catchError } from 'rxjs/operators';
import { EMPTY } from 'rxjs';
import { PreviewHeader } from '../../components/preview-header/PreviewHeader';
import SongItem from '../../components/song-item/SongItem';
import './album.css';
export default class AlbumPage extends Component<
  any,
  { album: any; isError: boolean }
> {
  constructor(props: any) {
    super(props);
    this.state = { isError: false, album: null };
  }
  componentDidMount() {
    const id = this.props.match.params.id;

    musicKitService
      .fetchAlbum(id)
      .pipe(
        catchError(_e => {
          this.setState({
            isError: true,
            album: null
          });
          return EMPTY;
        })
      )
      .subscribe(album => {
        console.log(album);
        this.setState({
          isError: true,
          album: album
        });
      });
  }

  render() {
    // return <div>{JSON.stringify(this.state.album)}</div>;
    return (
      <>
        {this.state.album !== null ? (
          <>
            <h1>{this.state.album.attributes.name}</h1>
            <PreviewHeader collection={this.state.album} />
            <ul>
              {this.state.album.relationships.tracks.data.map(
                (song: any, idx: number) => (
                  <SongItem song={song} index={idx} key={song.id} />
                )
              )}
            </ul>
          </>
        ) : null}
      </>
    );
  }
}

// vue-music-explorer/src/views/Album.vue
<template>
  <main>
    <div v-if="isLoading">Loading...</div>
    <template v-else>
      <h1>{{album.attributes.name}}</h1>
      <PreviewHeader :collection="album"/>
      <ul>
        <SongItem
          v-for="(song,i) in album.relationships.tracks.data"
          v-bind:key="song.id"
          :song="song"
          :index="i"
        />
      </ul>
    </template>
  </main>
</template>
<style scoped>
ul {
  padding: 0;
}
</style>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { musicKitService } from "@/services/musickit-service";
@Component({
  components: {
    PreviewHeader: () => import("@/components/PreviewHeader.vue"),
    SongItem: () => import("@/components/SongItem.vue")
  }
})
export default class AlbumPage extends Vue {
  isLoading: boolean = true;
  album: any;

  mounted() {
    const id = this.$route.params.id;
    musicKitService.fetchAlbum(id).subscribe(data => {
      this.album = data;
      this.isLoading = false;
    });
  }
}
</script>
