// react-music-explorer/src/pages/browse/Browse.tsx
import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import { AlbumPreviewItem } from '../../components/album-preview-item/AlbumPreviewItem';
import { musicKitService } from '../../services/musickit-service';
import './browse.css';
export default class BrowsePage extends Component<
  {},
  { isLoading: Boolean; topAlbums: any; topPlaylists: any }
> {
  constructor(props: any) {
    super(props);
    this.state = { isLoading: true, topAlbums: null, topPlaylists: null };
  }
  componentDidMount() {
    musicKitService.fetchChart().subscribe(res => {
      this.setState({
        topAlbums: res.albums[0].data,
        topPlaylists: res.playlists[0].data,
        isLoading: false
      });
    });
  }

  render() {
    return (
      <main>
        {this.state.isLoading ? <div>Loading...</div> : null}
        {this.state.topAlbums && this.state.topPlaylists ? (
          <>
            <h1>Top Albums</h1>
            <div className="top-list">
              {this.state.topAlbums.map((album: any, idx:number) => (
                <Link to={'album/' + album.id} key={album.id}>
                  <AlbumPreviewItem album={album} index={idx} />
                </Link>
              ))}
            </div>
            <h1>Top PlayLists</h1>
            <div className="top-list">
              {this.state.topPlaylists.map((playlist:any, idx:number) => (
                <Link to={'playlist/' + playlist.id} key={playlist.id}>
                  <AlbumPreviewItem album={playlist} index={idx} />
                </Link>
              ))}
            </div>
          </>
        ) : null}
      </main>
    );
  }
}

// vue-music-explorer/src/views/Browse.vue
<template>
  <main>
    <div v-if="isLoading">Loading...</div>

    <template v-else>
      <h1>Top Albums</h1>
      <div class="top-list">
        <router-link
          v-for="(album, index) in topAlbums"
          v-bind:key="album.id"
          :to="'/album/'+album.id"
        >
          <AlbumPreviewItem :album="album" :index="index"/>
        </router-link>
      </div>

      <h1>Top Playlists</h1>
      <div class="top-list">
        <router-link
          v-for="(playlist, index) in topPlaylists"
          v-bind:key="playlist.id"
          :to="'/playlist/'+playlist.id"
        >
          <AlbumPreviewItem :album="playlist" :index="index"/>
        </router-link>
      </div>
    </template>
  </main>
</template>
<style scoped>
h1 {
  font-weight: 700;
  margin-top: 5px;
  margin-bottom: 20px;
}

.top-list {
  display: flex;
  flex-wrap: wrap;
}
</style>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { musicKitService } from "@/services/musickit-service";
@Component({
  components: {
    AlbumPreviewItem: () => import('@/components/AlbumPreviewItem.vue')
  }
})
export default class BrowsePage extends Vue {
  topAlbums: any;
  topPlaylists: any;
  isLoading: boolean = true;

  mounted() {
    musicKitService.fetchChart().subscribe(data => {
      this.topAlbums = data.albums[0].data;
      this.topPlaylists = data.playlists[0].data;
      this.isLoading = false;
    });
  }
}
</script>
